VERSION_ADD_TABLE_NAME = 0
VERSION_ADD_NO_CRYPTED_WORD = 0
VERSION_ADD_EVERY_WORD_EXPANDED = 0
VERSION_STEPS = 0

# remember to set dataset name and set expland gold to 1 
EXPLAND_GOLD = 1
DATASET_NAME = "nameguess"